[tool.aerich]
tortoise_orm = "src/config.DATABASE_CONFIG"
location = "./migrations"
src_folder = "./src"

[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]
asyncio_mode="auto"
filterwarnings = [
  "ignore::DeprecationWarning"
]
